from pathlib import Path
from html import escape
import re
ROOT=Path(__file__).resolve().parent.parent
OUT=ROOT/'dist'
HOME=(ROOT/'src/home.html').read_text()
HEAD=(ROOT/'src/head.html').read_text().replace('href="style.css"','href="/style.css"')
NAV=[('/services/','Our services'),('/about/','About us'),('/shipping-guide/','Shipping guide'),('/locations/','Our locations'),('/contact/','Contact')]

def link(url,text,cls='button teal'):
 return f'<a class="{cls}" href="{url}">{text}<span aria-hidden="true">↗</span></a>'
def cta(title='Your next shipment starts here.',text='Tell us what you’re moving. Let’s find the right way forward.'):
 return f'<section class="section page-cta"><div><div class="eyebrow teal-text">LET’S MAKE YOUR NEXT MOVE</div><h2>{title}</h2><p>{text}</p></div>{link("/get-quote/","Get a shipping quote")}</section>'
def intro(eyebrow,title,desc,crumb,photo=False):
 return f'<section class="inner-hero {"with-photo" if photo else ""}"><div class="inner-hero-wrap"><div class="breadcrumbs"><a href="/">Home</a><span aria-hidden="true">/</span><span>{crumb}</span></div><div class="eyebrow"><span class="line"></span>{eyebrow}</div><h1>{title}</h1><p>{desc}</p></div><div class="inner-route" aria-hidden="true">CHINA <span>⟶</span> NIGERIA</div></section>'
def cards(items,cls='detail-grid'):
 return '<div class="'+cls+'">'+''.join(f'<article class="detail-card"><span class="card-number">0{i+1}</span><h3>{title}</h3><p>{text}</p></article>' for i,(title,text) in enumerate(items))+'</div>'
def faq(items):
 return '<div class="faq-list">'+''.join(f'<details><summary>{q}<span aria-hidden="true">+</span></summary><div><p>{a}</p></div></details>' for q,a in items)+'</div>'
FAQ=[
 ('How do I get a shipping quote?','Use our <a href="/get-quote/">quote form</a> to share your goods, quantity, approximate weight or dimensions, shipping method, and destination. It prepares a WhatsApp message for you to review and send. Our team confirms the charges after reviewing your shipment.'),
 ('Should I choose sea shipping or air freight?','Sea shipping is generally a practical option for larger cargo when timing is flexible. Air freight is worth discussing when timing matters more. Availability, suitability, cost, and expected timing are confirmed for your specific goods.'),
 ('How much will my shipment cost?','There is no published flat rate on this website. Tell us what you are sending and provide weight and package dimensions if available. Ask the team to confirm the charging basis, what is included, and any additional charges before booking.'),
 ('How long will delivery take?','Ask the team for the current estimate for your shipment before you book. Timing depends on the shipping method, departure schedule, cargo checks, and arrival arrangements. We do not promise an unconfirmed arrival date.'),
 ('Where do I send my goods in China?','Contact the China team before dispatch. The Guangzhou address listed on our <a href="/locations/#china-warehouse">locations page</a> is for the sea warehouse. For air freight, request the correct receiving instructions separately.'),
 ('How should my supplier label the packages?','Write the customer’s name, phone number, and destination city clearly on the outside of every package. Confirm any additional shipping mark with the receiving team before dispatch.'),
 ('Can I ship batteries, liquids, or fragile goods?','Tell the team exactly what the goods contain before sending them. Batteries, liquids, chemicals, fragile items, and other special cargo need a suitability check and may require specific handling. A quote request is not confirmation that an item is accepted.'),
 ('How do I get a shipment update?','Contact the team handling your shipment and share your customer name, shipment reference if provided, goods description, and the date you handed over your cargo. Updates are currently handled directly by our team.'),
 ('Where can I collect my goods in Nigeria?','We have offices in Lagos Island and Onitsha. Confirm your collection location and arrangements with the team before booking. For other cities, ask what options are available.'),
 ('What are the China sea warehouse receiving hours?','The supplied receiving hours are Monday to Saturday, 8:30–12:00 and 13:30–18:00, China time. Check with the China team before dispatch, especially around holidays.'),
 ('How do I pay for shipping?','Request an invoice and payment instructions directly from the company. Confirm the shipment details, charges, and payment recipient with your Bright Ocean contact before making payment.'),
 ('Does submitting a quote book my shipment?','No. The form helps you prepare an enquiry. You still need to send the message in WhatsApp and agree the shipping details and charges with our team.')]

# Keep the approved homepage composition, extending its links into the full website.
home=HOME.replace('href="#services"','href="/services/"').replace('href="#locations"','href="/locations/"')
home=home.replace('href="#quote" data-service="Sea shipping"','href="/services/sea-shipping/"').replace('href="#quote" data-service="Air freight"','href="/services/air-freight/"')
home=home.replace('Let’s talk sea freight','Explore sea shipping').replace('Let’s talk air freight','Explore air freight')
home=home.replace('Start your shipment <span>↗</span>','Read the shipping guide <span>↗</span>').replace('class="button outline" href="#quote"','class="button outline" href="/shipping-guide/"')
home=home.replace('The supplied English and Chinese address versions contain different street numbers.','Confirm the street number, receiving room, and shipping mark before your supplier sends any goods.')
home=home.replace('<form id="quote-form">','<form id="quote-form" action="https://wa.me/2348060227854" method="get">')
home=home.replace('<label>What are you shipping?', '<label class="other-city" hidden>Destination city<input name="city" placeholder="Your Nigerian city" maxlength="100"></label><label>What are you shipping?')
location_section=re.search(r'<section class="locations section".*?</section>',home,re.S).group()
warehouse=re.search(r'<details class="warehouse">.*?</details>',home,re.S).group()
quote_section=re.search(r'<section class="quote section".*?</section>',home,re.S).group()
service_cards=re.search(r'<div class="service-grid">.*?</div></section>',home,re.S).group().removesuffix('</section>')

pages={}
pages['/']=('China to Nigeria Sea & Air Freight','Sea shipping and air freight from China to Nigeria. Connect with Bright Ocean Logistics in Guangzhou, Lagos and Onitsha.',home)

pages['/services/']=('Our Shipping Services','Explore sea shipping and air freight from China to Nigeria with Bright Ocean Logistics.',
 intro('OUR SERVICES','Two ways to move.<br><em>One bright connection.</em>','Sea shipping and air freight, built around what you need to move. Start with your cargo. We’ll help you with the next step.','Our services')+
 '<section class="section"><div class="section-heading"><div><div class="eyebrow teal-text">FIND YOUR FIT</div><h2>The right route<br>for your next order.</h2></div><p>Your priorities shape the journey. Tell us about your goods, your destination, and the timing you have in mind.</p></div>'+service_cards+'</section>'+
 '<section class="section soft-section"><div class="section-heading"><div><div class="eyebrow teal-text">AT A GLANCE</div><h2>Sea or air?</h2></div><p>A starting point for your conversation with our team.</p></div><div class="comparison-wrap"><table class="comparison"><caption class="sr-only">Comparison of sea shipping and air freight</caption><thead><tr><th scope="col">Your priority</th><th scope="col">Sea shipping</th><th scope="col">Air freight</th></tr></thead><tbody><tr><th scope="row">Cargo profile</th><td>Larger or bulkier shipments</td><td>Time-sensitive consignments</td></tr><tr><th scope="row">Timing</th><td>Plan ahead with a flexible timeline</td><td>Discuss a faster shipping option</td></tr><tr><th scope="row">Receiving in China</th><td>Confirm Guangzhou sea warehouse details</td><td>Request air cargo receiving details</td></tr><tr><th scope="row">Pricing & acceptance</th><td>Confirmed for your cargo</td><td>Confirmed for your cargo</td></tr></tbody></table></div></section>'+cta('Not sure which way to go?','Send us the details. We’ll help you weigh up the options.'))

for mode in ('sea','air'):
 sea=mode=='sea'
 name='Sea shipping' if sea else 'Air freight'
 slug='/services/sea-shipping/' if sea else '/services/air-freight/'
 lead='More room for<br><em>big possibilities.</em>' if sea else 'For the moves<br><em>that matter now.</em>'
 desc='A practical ocean route for goods moving from China to Nigeria. Plan ahead and make space for your next big order.' if sea else 'Keep your business moving when timing matters. Discuss air cargo options for your next shipment from China to Nigeria.'
 points=[('Space for your next order','Discuss larger consignments, packaged goods, and bulk cargo with our team.'),('Plan with confidence','Confirm current shipping arrangements and the expected schedule before sending your goods.'),('A local point of contact','Coordinate your shipment with our China contacts and the Lagos or Onitsha office.')] if sea else [('Time-sensitive shipments','Tell us your deadline so we can discuss the current air freight options.'),('Cargo checked first','Share the contents, packaging, weight, and any batteries or liquids before dispatch.'),('Clear receiving instructions','Ask for the correct air cargo receiving address. The published Guangzhou warehouse is for sea shipments.')]
 body=intro('OUR SERVICES / '+('OCEAN' if sea else 'AIR'),lead,desc,'<a href="/services/">Our services</a> / '+name,sea)
 body+='<section class="section content-with-aside"><div><div class="eyebrow teal-text">'+name.upper()+'</div><h2>'+('A bigger journey.<br>A clear next step.' if sea else 'Move with purpose.<br>Start with the details.')+'</h2><p class="lead-copy">'+('For businesses bringing goods into Nigeria, the ocean route can be a practical choice when volume matters and the timeline is flexible. Every consignment starts with a conversation about your cargo.' if sea else 'For an urgent order or an important consignment, talk to us about air freight. The best arrangement depends on the goods, their size and weight, and when they need to move.')+'</p>'+cards(points,'detail-stack')+'</div><aside class="shipping-aside"><div class="eyebrow teal-text">YOUR SHIPMENT, AT A GLANCE</div><h3>'+name+'</h3><dl><div><dt>Origin</dt><dd>China</dd></div><div><dt>Destination</dt><dd>Nigeria</dd></div><div><dt>Nigeria contacts</dt><dd>Lagos & Onitsha</dd></div><div><dt>Price & timing</dt><dd>Confirmed with your quote</dd></div></dl>'+link('/get-quote/?service='+('sea' if sea else 'air'),'Request a quote')+'<a class="aside-link" href="/contact/">Talk to our team ↗</a></aside></section>'
 body+='<section class="section soft-section"><div class="section-heading"><div><div class="eyebrow teal-text">BEFORE YOU SHIP</div><h2>A little preparation.<br>A smoother handover.</h2></div><p>Have these details ready when you contact us.</p></div>'+cards([('Describe your goods','Product type, quantities, and any special contents or handling needs.'),('Share the package details','Number of packages, approximate weight, and length × width × height if available.'),('Choose your destination','Tell us your city and discuss the receiving or collection arrangements.')])+'</section>'
 body+='<section class="section narrow-section"><div class="eyebrow teal-text">A FEW USEFUL ANSWERS</div><h2>Before your first shipment.</h2>'+faq([FAQ[2],FAQ[3],FAQ[4] if sea else FAQ[6]])+'</section>'+cta()
 pages[slug]=(name+' from China to Nigeria',desc.replace('<br>',' '),body)

pages['/about/']=('About Bright Ocean','Meet Bright Ocean Logistics Co. Services LTD, connecting cargo from China with businesses in Nigeria.',
 intro('ABOUT BRIGHT OCEAN','Across oceans.<br><em>Closer to your business.</em>','Trade connects places. People make it happen. We bring a human connection to sea shipping and air freight between China and Nigeria.','About us',True)+
 '<section class="section editorial-split"><div><div class="eyebrow teal-text">BRIGHT OCEAN LOGISTICS CO. SERVICES LTD</div><h2>A connection you can<br>put a name to.</h2></div><div class="editorial-copy"><p>Bright Ocean Logistics helps customers arrange sea shipping and air freight from China to Nigeria, with contacts in Guangzhou and offices in Lagos and Onitsha.</p><p>Whether you’re planning your next order or discussing a time-sensitive shipment, start with a conversation. Our team can review your cargo details, explain the arrangements, and confirm the next steps.</p>'+link('/contact/','Meet your points of contact','text-link teal-text')+'</div></section>'+
 '<section class="section soft-section"><div class="section-heading"><div><div class="eyebrow teal-text">THE WAY WE WORK</div><h2>Real conversations.<br>Practical next steps.</h2></div></div>'+cards([('Start with your cargo','We ask about the goods, packaging, destination, and timing so the conversation starts with what your shipment needs.'),('Confirm before dispatch','Receiving instructions, charges, and shipment arrangements should be agreed before your supplier sends the goods.'),('Keep a local connection','Speak with the China contacts or your Nigeria office as you prepare your shipment and arrange collection.')])+'</section>'+
 '<section class="section network-section"><div class="eyebrow teal-text">OUR CONNECTION</div><h2>Three places.<br>One shared journey.</h2><div class="network-row"><div><span>01 / CHINA</span><h3>Guangzhou</h3><p>Sea warehouse contacts</p></div><span class="network-arrow" aria-hidden="true">⟶</span><div><span>02 / NIGERIA</span><h3>Lagos</h3><p>Lagos Island office</p></div><span class="network-arrow" aria-hidden="true">⟶</span><div><span>03 / NIGERIA</span><h3>Onitsha</h3><p>Anambra State office</p></div></div>'+link('/locations/','Find our locations','button outline')+'</section>'+cta())

pages['/shipping-guide/']=('Shipping Guide','Prepare your China to Nigeria shipment: cargo details, warehouse labels, receiving instructions, and collection.',
 intro('YOUR SHIPPING GUIDE','A clear path.<br><em>From first enquiry to arrival.</em>','Your first shipment or your next one—get the essentials in place before the goods start moving.','Shipping guide')+
 '<section class="section content-with-aside"><div class="journey-steps">'+''.join(f'<article><div class="journey-number">0{i+1}</div><div><span class="eyebrow teal-text">{tag}</span><h2>{title}</h2><p>{text}</p></div></article>' for i,(tag,title,text) in enumerate([
 ('START THE CONVERSATION','Tell us what’s moving.','Describe the goods, number of packages, approximate weight, dimensions, destination city, and any timing needs. Mention special contents such as batteries, liquids, or fragile items.'),
 ('AGREE THE ARRANGEMENTS','Confirm the details.','Discuss sea or air freight, current pricing, what the charges include, and expected timing. Get the correct receiving instructions before your supplier dispatches anything.'),
 ('PREPARE YOUR PACKAGES','Label every piece.','Ask your supplier to write your customer name, phone number, and destination city clearly on each package. Confirm any additional shipping mark and packaging requirements with the team.'),
 ('HAND OVER IN CHINA','Coordinate with the receiving team.','Confirm the delivery address and receiving hours. Keep the supplier’s dispatch details and ask the team how receipt of your goods will be confirmed.'),
 ('STAY IN TOUCH','Arrange the Nigeria handover.','Contact the team for shipment updates. Confirm the collection office, any remaining charges, and what you need to bring before travelling to collect your goods.')]))+'</div><aside class="shipping-aside"><div class="eyebrow teal-text">READY TO GET STARTED?</div><h3>Your enquiry checklist</h3><ul class="checklist"><li>Product description</li><li>Number of packages</li><li>Weight or dimensions</li><li>Destination city</li><li>Preferred shipping method</li><li>Your contact details</li></ul>'+link('/get-quote/','Prepare your enquiry')+'<a class="aside-link" href="/faq/">Read common questions ↗</a></aside></section>'+
 '<section class="section soft-section"><div class="section-heading"><div><div class="eyebrow teal-text">ON THE OUTSIDE OF EVERY PACKAGE</div><h2>A clear label goes a long way.</h2></div><p>Give your supplier the customer details the receiving team needs.</p></div><div class="label-guide"><div class="sample-label"><span>SHIPPING LABEL / EXAMPLE</span><strong>CUSTOMER: [Your full name]</strong><strong>PHONE: [Your phone number]</strong><strong>CITY: [Your destination city]</strong><div>Confirm any additional shipping mark with our team.</div></div><div><h3>Before your supplier dispatches</h3><p>Check the label, package count, and receiving address together. The Guangzhou address on this site is the sea warehouse; air freight needs separate confirmation.</p>'+link('/locations/#china-warehouse','View warehouse details','text-link teal-text')+'</div></div></section>'+cta())

locations=location_section.replace('id="locations"','id="office-directory"').replace('<div class="eyebrow teal-text">03 / LOCAL TEAMS. GLOBAL REACH.</div>','<div class="eyebrow teal-text">OUR OFFICE DIRECTORY</div>')
locations=locations.replace('<details class="warehouse">','<details class="warehouse" id="china-warehouse" open>')
locations=locations.replace('class="location-card"><div class="location-label">NIGERIA <span>01','class="location-card" id="lagos"><div class="location-label">NIGERIA <span>01').replace('class="location-card"><div class="location-label">NIGERIA <span>02','class="location-card" id="onitsha"><div class="location-label">NIGERIA <span>02')
locations=locations.replace('NDC · +234 904 112 4666 ↗</a>','NDC · +234 904 112 4666 ↗</a><a class="map-link" href="https://www.google.com/maps/search/?api=1&amp;query=Fulham+Plaza+Lagos+Island" target="_blank" rel="noopener">Search address on Maps ↗</a>')
locations=locations.replace('Ogochukwu · +234 903 341 2782 ↗</a>','Ogochukwu · +234 903 341 2782 ↗</a><a class="map-link" href="https://www.google.com/maps/search/?api=1&amp;query=Diamond+Plaza+45+Sokoto+Road+Onitsha" target="_blank" rel="noopener">Search address on Maps ↗</a>')
locations=locations.replace('Chen · +86 153 8147 6562 ↗</a>','Chen · +86 153 8147 6562 ↗</a><a href="tel:+8619988270008">阿俊 · +86 199 8827 0008 ↗</a>')
pages['/locations/']=('Our Locations','Find Bright Ocean Logistics offices in Lagos and Onitsha and China sea warehouse receiving details.',intro('OUR LOCATIONS','Here for you.<br><em>On both sides of the ocean.</em>','Find your nearest office or connect with our China warehouse contacts before sending your shipment.','Our locations')+locations+'<section class="section compact-section"><div class="notice-card"><h3>A quick note before visiting</h3><p>Call your chosen office to confirm directions and availability. For China deliveries, confirm the exact street number, room, shipping mark, and receiving schedule with Ali before dispatch.</p></div></section>'+cta())

pages['/contact/']=('Contact Our Team','Contact Bright Ocean Logistics by WhatsApp, phone, or email for China to Nigeria shipping enquiries.',
 intro('CONTACT US','A real person.<br><em>A brighter next step.</em>','A shipping question, a new order, or an update on goods already moving—let’s get you to the right conversation.','Contact')+
 '<section class="section contact-grid"><article class="contact-primary"><div class="eyebrow teal-text">GENERAL ENQUIRIES</div><h2>Let’s talk cargo.</h2><p>For a new shipment or a general question, reach our main contact directly.</p><a class="large-contact" href="tel:+2348060227854">+234 806 022 7854</a><a class="contact-email" href="mailto:bw020930@gmail.com">bw020930@gmail.com</a>'+link('https://wa.me/2348060227854','Chat on WhatsApp')+'</article><div class="contact-options"><article><span class="eyebrow teal-text">PLANNING A SHIPMENT?</span><h3>Start with a quote.</h3><p>Share the cargo details once, in a clear message to our team.</p>'+link('/get-quote/','Request a shipping quote','text-link')+'</article><article><span class="eyebrow teal-text">CARGO ALREADY MOVING?</span><h3>Ask for a shipment update.</h3><p>Have your customer name, shipment reference if provided, and dispatch date ready.</p>'+link('https://wa.me/2348060227854?text=Hello%20Bright%20Ocean%2C%20I%20would%20like%20an%20update%20on%20my%20shipment.','Contact the team','text-link')+'</article></div></section>'+
 '<section class="section soft-section"><div class="section-heading"><div><div class="eyebrow teal-text">SPEAK TO YOUR LOCAL CONTACT</div><h2>Closer to your shipment.</h2></div>'+link('/locations/','View office addresses','button outline')+'</div>'+re.search(r'<div class="location-grid">.*?</div><details',locations,re.S).group().removesuffix('<details')+'</section>'+
 '<section class="section narrow-section"><div class="eyebrow teal-text">BEFORE YOU GET IN TOUCH</div><h2>You might find it here.</h2>'+faq([FAQ[0],FAQ[4],FAQ[7]])+'</section>')

quote=quote_section.replace('04 / YOUR NEXT MOVE','YOUR NEXT MOVE').replace('<h2>Good things','<h1>Good things').replace('are on the <em>way.</em></h2>','are on the <em>way.</em></h1>')
quote=quote.replace('<form id="quote-form"','<form id="quote-form"')
quote=quote.replace('<p class="form-help">','<div class="form-status" role="status" hidden></div><p class="form-help">')
pages['/get-quote/']=('Request a Shipping Quote','Prepare a sea shipping or air freight enquiry from China to Nigeria and send it to Bright Ocean Logistics on WhatsApp.', '<div class="quote-breadcrumb section"><div class="breadcrumbs"><a href="/">Home</a><span>/</span><span>Get a quote</span></div></div>'+quote+'<section class="section quote-after"><div><div class="eyebrow teal-text">WHAT HAPPENS NEXT?</div><h2>One message.<br>A useful conversation.</h2></div>'+cards([('Review your message','Your details are prepared in WhatsApp. Check them and send when you are ready.'),('Discuss the shipment','Our team reviews your cargo and discusses the route, charges, and receiving instructions.'),('Confirm before dispatch','Agree the arrangements before your supplier sends the goods. An enquiry is not a booking.')])+'</section>')
pages['/faq/']=('Frequently Asked Questions','Answers to common questions about Bright Ocean Logistics shipping quotes, sea and air freight, receiving goods, and shipment updates.',intro('HELP & ANSWERS','A little clarity.<br><em>Before the journey.</em>','Useful answers to the questions that come up before, during, and after a shipment.','Frequently asked questions')+'<section class="section faq-layout"><aside class="faq-aside"><div class="eyebrow teal-text">QUICK LINKS</div><a href="#planning">Planning & pricing</a><a href="#preparing">Preparing your cargo</a><a href="#updates">Updates & collection</a><div class="help-card"><h3>Need a specific answer?</h3><p>Tell us about your shipment.</p>'+link('/contact/','Talk to the team','text-link')+'</div></aside><div><section id="planning" class="faq-group"><h2>Planning & pricing</h2>'+faq(FAQ[:4]+[FAQ[11]])+'</section><section id="preparing" class="faq-group"><h2>Preparing your cargo</h2>'+faq(FAQ[4:7]+[FAQ[9]])+'</section><section id="updates" class="faq-group"><h2>Updates & collection</h2>'+faq([FAQ[7],FAQ[8],FAQ[10]])+'</section></div></section>'+cta())


def render(route,title,desc,body):
 head=re.sub(r'<title>.*?</title>',f'<title>{escape(title)} | Bright Ocean Logistics</title>',HEAD)
 head=re.sub(r'<meta name="description" content="[^"]*">',f'<meta name="description" content="{escape(desc,quote=True)}">',head)
 nav=''.join(f'<a href="{url}"'+(' aria-current="page"' if route==url or (url=='/services/' and route.startswith('/services/')) else '')+f'>{label}</a>' for url,label in NAV)
 header=f'<a class="skip-link" href="#main-content">Skip to content</a><div class="topbar"><span>Connecting China and Nigeria. Moving your business forward.</span><a href="mailto:bw020930@gmail.com">bw020930@gmail.com <span>↗</span></a></div><header><a class="brand" href="/" aria-label="Bright Ocean home"><img src="/assets/logo.png" width="180" height="98" alt="Bright Ocean Logistics"></a><nav id="main-nav" aria-label="Main navigation">{nav}</nav><a class="button dark nav-cta" href="/get-quote/">Get a shipping quote <span>↗</span></a><button class="menu-toggle" aria-label="Open menu" aria-expanded="false" aria-controls="main-nav"><span class="menu-bars" aria-hidden="true"></span></button></header>'
 footer='<footer><div class="footer-top"><div><a class="footer-brand" href="/">Bright Ocean<span>LOGISTICS</span></a><p>Moving cargo. Connecting possibilities.</p><a class="footer-email" href="mailto:bw020930@gmail.com">bw020930@gmail.com</a></div><div><span>EXPLORE</span><a href="/about/">About Bright Ocean</a><a href="/services/sea-shipping/">Sea shipping</a><a href="/services/air-freight/">Air freight</a><a href="/locations/">Our locations</a></div><div><span>HOW CAN WE HELP?</span><a href="/shipping-guide/">Shipping guide</a><a href="/faq/">Common questions</a><a href="/get-quote/">Request a quote</a><a href="/contact/">Contact our team</a></div><div><span>FOLLOW THE JOURNEY</span><a href="https://www.instagram.com/bright_ocean_logistice/" target="_blank" rel="noopener">Instagram ↗</a><a href="https://www.tiktok.com/@brightocean123" target="_blank" rel="noopener">TikTok ↗</a><a href="tel:+2348060227854">+234 806 022 7854</a></div></div><div class="footer-bottom"><span>© <span id="year">2026</span> Bright Ocean Logistics Co. Services LTD</span><a href="#top">Back to top ↑</a><span>CHINA → NIGERIA</span></div></footer>'
 return '<!doctype html>\n<html lang="en"><head>'+head+'</head><body id="top" class="'+('home-page' if route=='/' else 'inner-page')+'">'+header+'<main id="main-content" tabindex="-1">'+body+'</main>'+footer+'<script src="/app.js" defer></script></body></html>\n'
for route,(title,desc,body) in pages.items():
 target=OUT/route.strip('/')/'index.html'
 target.parent.mkdir(parents=True,exist_ok=True)
 target.write_text(render(route,title,desc,body))
(OUT/'404.html').write_text(render('/404/','Page Not Found','Find your way back to Bright Ocean Logistics.',intro('404 / A DIFFERENT DIRECTION','Let’s get you<br><em>back on course.</em>','This page may have moved, or the link may be incomplete. Your next shipping conversation is still just a click away.','Page not found')+'<section class="section error-actions">'+link('/','Back to home')+link('/contact/','Contact us','button outline')+'</section>'))
print(f'Built {len(pages)} pages and a custom 404 page.')
